<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-09T16:55:20 IST" name="Suite" finished-at="2024-10-09T16:55:29 IST" duration-ms="9377">
    <groups>
      <group name="integration">
        <method signature="TCIntegration_Retry.testDeleteBooking(org.testng.ITestContext)[pri:4, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" name="testDeleteBooking" class="tests.Integration.TCIntegration_Retry"/>
        <method signature="TCIntegration_Retry.testGetRequest(org.testng.ITestContext)[pri:2, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" name="testGetRequest" class="tests.Integration.TCIntegration_Retry"/>
        <method signature="TCIntegration_Retry.testUpdateBooking(org.testng.ITestContext)[pri:3, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" name="testUpdateBooking" class="tests.Integration.TCIntegration_Retry"/>
        <method signature="TCIntegration_Retry.testcreateBooking(org.testng.ITestContext)[pri:1, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" name="testcreateBooking" class="tests.Integration.TCIntegration_Retry"/>
      </group> <!-- integration -->
    </groups>
    <test started-at="2024-10-09T16:55:20 IST" name="Test" finished-at="2024-10-09T16:55:29 IST" duration-ms="9377">
      <class name="tests.Integration.TCIntegration_Retry">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" started-at="2024-10-09T16:55:20 IST" name="setup" finished-at="2024-10-09T16:55:20 IST" duration-ms="642" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testcreateBooking(org.testng.ITestContext)[pri:1, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" started-at="2024-10-09T16:55:20 IST" name="testcreateBooking" finished-at="2024-10-09T16:55:25 IST" duration-ms="4755" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@673bb956]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcreateBooking -->
        <test-method signature="testGetRequest(org.testng.ITestContext)[pri:2, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" started-at="2024-10-09T16:55:25 IST" name="testGetRequest" finished-at="2024-10-09T16:55:26 IST" duration-ms="1235" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@673bb956]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetRequest -->
        <test-method signature="testUpdateBooking(org.testng.ITestContext)[pri:3, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" started-at="2024-10-09T16:55:26 IST" name="testUpdateBooking" finished-at="2024-10-09T16:55:28 IST" duration-ms="1221" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@673bb956]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateBooking -->
        <test-method signature="testDeleteBooking(org.testng.ITestContext)[pri:4, instance:tests.Integration.TCIntegration_Retry@58cbafc2]" started-at="2024-10-09T16:55:28 IST" name="testDeleteBooking" finished-at="2024-10-09T16:55:29 IST" duration-ms="1370" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@673bb956]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> but was <201>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <201>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at tests.Integration.TCIntegration_Retry.testDeleteBooking(TCIntegration_Retry.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteBooking -->
      </class> <!-- tests.Integration.TCIntegration_Retry -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
